version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: namachan10777/s8:latest

    working_directory: ~/coins-reports

    steps:
      - checkout

      - run:
          name: submodule update
          command: git submodule update --init --recursive
      - run:
          name: test code
          command: cd code && eval $(opam env) && dune runtest

      - run:
          name: test compiler
          command: eval $(opam env) && make test -C compiler

      - run:
          name: build document
          command: eval $(opam env) && make all

      - store_artifacts:
          path: dist
